// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (*Account, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteInstanceIdentityDocument(ctx context.Context, clientID uuid.UUID) error
	DeleteServiceAccount(ctx context.Context, clientID uuid.UUID) error
	DeleteUser(ctx context.Context, username string) error
	GetCertificate(ctx context.Context, serialNumber string) (*Certificate, error)
	GetInstanceIdentityDocument(ctx context.Context, clientID uuid.UUID) (*AwsAttestation, error)
	GetServiceAccounts(ctx context.Context, serviceAccount string) ([]*Account, error)
	GetServiceUUID(ctx context.Context, clientID uuid.UUID) (*Account, error)
	GetUser(ctx context.Context, username string) (*User, error)
	ListCertificateSubjectAlternativeName(ctx context.Context, arg ListCertificateSubjectAlternativeNameParams) ([]*Certificate, error)
	ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]*Certificate, error)
	ListServiceAccounts(ctx context.Context, arg ListServiceAccountsParams) ([]*Account, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error)
	LogCertificate(ctx context.Context, arg LogCertificateParams) (*Certificate, error)
	RevokeIssuedCertificateSerialNumber(ctx context.Context, arg RevokeIssuedCertificateSerialNumberParams) error
	StoreInstanceIdentityDocument(ctx context.Context, arg StoreInstanceIdentityDocumentParams) (*AwsAttestation, error)
	UpdateInstanceIdentityNodeAttestor(ctx context.Context, arg UpdateInstanceIdentityNodeAttestorParams) (*Account, error)
	UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) (*Account, error)
	UpdateUserAuthentication(ctx context.Context, arg UpdateUserAuthenticationParams) (*User, error)
	UpdateUserPermission(ctx context.Context, arg UpdateUserPermissionParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
