name: PR Build

on: 
  pull_request: {}


jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y make

      - name: Build baseca Executable
        run: make build

      - name: baseca Unit Test
        run: make test

      - name: Build baseca Container
        run: docker build -f Dockerfile -t baseca .